<?php ob_start();?>

<!DOCTYPE html>
<html>
  <head>
  <meta charset='utf-8'>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato:400,400i" rel="stylesheet" type="text/css">
  <!--<link href="https://fonts.googleapis.com/css?family=Open+Sans:700,700i" rel="stylesheet" type="text/css">-->
  <?php include BASE_PATH . 'helperclasses/PDFStyles/Main.php'; ?>
  <title>Generated PDF</title>
  </head>
  <body>
    <?php include BASE_PATH . 'helperclasses/PDFStyles/Letterhead.php'; ?>
    <div class="primary-box mb-3" id="test">
      <h1>
        Welcome to <?=CLUB_NAME?>
      </h1>

      <p class="mb-0">
        Let's get you set up with your account
      </p>
    </div>
    <p>
      This document was generated by <strong><?=getUserName($_SESSION['UserID'])?></strong>.
    </p>
    <p>
      This is a test document to test various HTML elements with dompdf.
    </p>

    <h2>
      A test link
    </h2>

    <p>
      If you do not have a device that can read QR Codes, to add a swimmer, log into your account at <a href="<?=autoUrl("")?>"><?=autoUrl("")?></a> and the select ‘My Account’ then ‘Add Swimmers’ from the menu at the top.
    </p>

    <p>
      Test link to <a href="#test">part of document</a>.
    </p>

    <h2>
      Demonstration lists
    </h2>

    <ul>
      <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
      <li>In fermentum nunc sit amet tincidunt porttitor.</li>
      <li>Nunc condimentum nibh ac nisi varius pulvinar.</li>
    </ul>

    <ul>
      <li>Maecenas porttitor sapien non dapibus fermentum.</li>
      <li>Morbi eleifend odio quis molestie porttitor.</li>
      <li>Etiam non tellus ut nunc aliquam ornare.</li>
      <li>Proin non ex tristique, aliquam mi a, interdum mauris.</li>
    </ul>

    <ul>
      <li>Fusce vehicula quam sed risus vehicula molestie.</li>
    </ul>

    <h2>
      A test table
    </h2>

    <p>
      Tables are important in printed documents, so it's important we include one to test here.
    </p>

    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">First</th>
          <th scope="col">Last</th>
          <th scope="col">Handle</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">1</th>
          <td>Mark</td>
          <td>Otto</td>
          <td>@mdo</td>
        </tr>
        <tr>
          <th scope="row">2</th>
          <td>Jacob</td>
          <td>Thornton</td>
          <td>@fat</td>
        </tr>
        <tr>
          <th scope="row">3</th>
          <td>Larry</td>
          <td>the Bird</td>
          <td>@twitter</td>
        </tr>
      </tbody>
    </table>

    <div class="page-break"></div>

    <h2 class="primary">
      Primary text
    </h2>

    <p class="primary">
      This paragraph and associated title is in the <?=CLUB_NAME?> Membership House Colour
    </p>

    <h2>
      Primary box
    </h2>

    <div class="primary-box mb-3" id="test">
      <h2>
        White text in a primary box
      </h2>

      <p class="mb-0">
        This paragraph and associated title is white in a box which is in the <?=CLUB_NAME?> Membership House Colour
      </p>
    </div>
    <?php include BASE_PATH . 'helperclasses/PDFStyles/PageNumbers.php'; ?>
  </body>
</html>

<?php

$html = ob_get_clean();

// reference the Dompdf namespace
use Dompdf\Dompdf;

// instantiate and use the dompdf class
$dompdf = new Dompdf();

// set font dir here
$dompdf->set_option('font_dir', BASE_PATH . 'fonts/');

$dompdf->set_option('defaultFont', 'Open Sans');
$dompdf->set_option('defaultMediaType', 'all');
$dompdf->set_option("isPhpEnabled", true);
$dompdf->set_option('isFontSubsettingEnabled', false);
$dompdf->loadHtml($html);

// (Optional) Setup the paper size and orientation
$dompdf->setPaper('A4', 'portrait');

// Render the HTML as PDF
$dompdf->render();

// Output the generated PDF to Browser
header('Content-Description: File Transfer');
header('Content-Type: application/pdf');
header('Content-Disposition: inline');
header('Expires: 0');
header('Cache-Control: must-revalidate');
header('Pragma: public');
$dompdf->stream("TestPDF.pdf", ['Attachment' => 0]);
