<?php ob_start();?>

<!DOCTYPE html>
<html>
  <head>
  <meta charset='utf-8'>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,400i" rel="stylesheet" type="text/css">
  <!--<link href="https://fonts.googleapis.com/css?family=Open+Sans:700,700i" rel="stylesheet" type="text/css">-->
  <?php include BASE_PATH . 'helperclasses/PDFStyles/Main.php'; ?>
  <title>Generated PDF</title>
  </head>
  <body>
    <?php include BASE_PATH . 'helperclasses/PDFStyles/Letterhead.php'; ?>

    <address class="mb-3 address-font address-box">
      <strong>Forename Surname</strong><br>
      1 Any Street<br>
      Address Line 2<br>
      Newcastle-upon-Tyne<br>
      NE99 1AA
    </address>
    <div class="after-address-box"></div>

    <div class="primary-box mb-3 window-c5-spacer" id="test">
      <h1>
        Welcome to <?=htmlspecialchars(app()->tenant->getKey('CLUB_NAME'))?>
      </h1>

      <p class="mb-0">
        Let's get you set up with your account
      </p>
    </div>

    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse pellentesque, orci at laoreet tincidunt, turpis justo ullamcorper justo, id cursus massa purus ut velit. Nulla at libero mi. Nulla quis neque non turpis consectetur semper eu at dui. Nulla facilisi. Pellentesque aliquet, tellus vitae venenatis tincidunt, urna metus pharetra nunc, quis lobortis leo est non purus. Cras laoreet gravida nulla sollicitudin porttitor. Pellentesque eu nisi vitae sapien pretium fringilla sit amet vitae purus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut tortor semper, gravida velit vitae, aliquet lacus. Nam tempus efficitur quam, a iaculis tellus posuere malesuada.</p>

    <p>Ut in ex commodo, porta lacus aliquet, bibendum tortor. Praesent non dui felis. Proin vitae nibh odio. Donec tempor, leo non elementum semper, massa risus tincidunt ex, in mattis enim ex eu felis. Aliquam lacinia blandit ligula non cursus. Quisque sagittis tortor mattis ex tempor, sed eleifend risus pellentesque. Etiam felis leo, imperdiet sit amet placerat ac, mattis vel diam. Mauris eu vestibulum dui. Sed elit diam, vehicula non ex at, efficitur feugiat magna. Aenean et lorem eget mauris ultrices ultricies. Praesent dapibus ut purus ut mattis..</p>

    <p>Donec vel erat congue dui tempus pulvinar at et quam. Aliquam non metus vel odio volutpat dictum at at mi. Aenean iaculis neque ac placerat ultricies. Cras eu elit neque. Etiam at faucibus enim. Quisque congue augue tellus, quis congue diam vulputate quis. Aliquam eleifend, libero ac sollicitudin ullamcorper, ligula mi convallis velit, ac hendrerit est metus bibendum lacus. Integer sit amet sagittis mi. Quisque vestibulum vehicula lectus sagittis imperdiet. Suspendisse potenti. Morbi in eleifend libero..</p>

    <p>Sed accumsan vulputate urna, ac euismod felis efficitur vitae. Donec fermentum fringilla libero, ac lacinia nisl finibus at. Nunc ornare lacus a dui finibus, sed tempus ante rutrum. Aenean facilisis odio ac faucibus aliquam. Nulla in velit ligula. Quisque varius ante nisi, eu blandit orci scelerisque et. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nam mollis risus sed est ultricies, id condimentum erat maximus. Praesent ut ex vel nibh porta faucibus. Integer tristique pharetra molestie..</p>

    <p>Maecenas non tellus nisl. Sed placerat vulputate urna id pretium. Aliquam accumsan a mi in rhoncus. Curabitur ut dolor et nisi rutrum molestie gravida ac arcu. Aliquam commodo magna in ullamcorper scelerisque. Pellentesque at tristique ligula, at euismod orci. Morbi id elit hendrerit, dapibus massa sit amet, tempor nibh. Maecenas vel nibh feugiat, finibus mauris nec, dictum nisi. Nullam nisi nisi, lacinia et tellus ut, fringilla ultrices metus. Cras porttitor felis non nisi tempus tempus. Aenean nibh massa, congue et porta in, luctus in dui. Suspendisse interdum elementum dui eget accumsan. Integer imperdiet tempus turpis, vel congue dolor tempor sit amet. Morbi consectetur rhoncus sodales. Aliquam ac justo tempor est aliquam lacinia. Nulla viverra ac justo sit amet placerat.</p>

    <p>
      This document was generated by
      <strong><?=getUserName($_SESSION['TENANT-' . app()->tenant->getId()]['UserID'])?></strong> and demonstrates
      how Membership can generate PDF files on the fly.
    </p>
    <p>
      This is a test document to test various HTML elements with dompdf.
    </p>

    <h2>
      A test link
    </h2>

    <p>
      If you do not have a device that can read QR Codes, to add a swimmer, log into your account at <a href="<?=autoUrl("")?>"><?=autoUrl("")?></a> and the select ‘My Account’ then ‘Add Swimmers’ from the menu at the top.
    </p>

    <p>
      Test link to <a href="#test">part of document</a>.
    </p>

    <h2>
      Demonstration lists
    </h2>

    <ul>
      <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
      <li>In fermentum nunc sit amet tincidunt porttitor.</li>
      <li>Nunc condimentum nibh ac nisi varius pulvinar.</li>
    </ul>

    <ul>
      <li>Maecenas porttitor sapien non dapibus fermentum.</li>
      <li>Morbi eleifend odio quis molestie porttitor.</li>
      <li>Etiam non tellus ut nunc aliquam ornare.</li>
      <li>Proin non ex tristique, aliquam mi a, interdum mauris.</li>
    </ul>

    <ul>
      <li>Fusce vehicula quam sed risus vehicula molestie.</li>
    </ul>

    <h2>
      Signature box
    </h2>
    <p>Please sign the box below to indicate X.</p>
    <input style="width:10cm;height: 1cm;" type="text" name="x">

    <h2>
      A test table
    </h2>

    <p>
      Tables are important in printed documents, so it's important we include one to test here.
    </p>

    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">First</th>
          <th scope="col">Last</th>
          <th scope="col">Handle</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">1</th>
          <td>Mark</td>
          <td>Otto</td>
          <td>@mdo</td>
        </tr>
        <tr>
          <th scope="row">2</th>
          <td>Jacob</td>
          <td>Thornton</td>
          <td>@fat</td>
        </tr>
        <tr>
          <th scope="row">3</th>
          <td>Larry</td>
          <td>the Bird</td>
          <td>@twitter</td>
        </tr>
        <tr>
          <th scope="row">4</th>
          <td>Mark</td>
          <td>Otto</td>
          <td>@mdo</td>
        </tr>
        <tr>
          <th scope="row">5</th>
          <td>Jacob</td>
          <td>Thornton</td>
          <td>@fat</td>
        </tr>
        <tr>
          <th scope="row">6</th>
          <td>Larry</td>
          <td>the Bird</td>
          <td>@twitter</td>
        </tr>
        <tr>
          <th scope="row">7</th>
          <td>Mark</td>
          <td>Otto</td>
          <td>@mdo</td>
        </tr>
        <tr>
          <th scope="row">8</th>
          <td>Jacob</td>
          <td>Thornton</td>
          <td>@fat</td>
        </tr>
        <tr>
          <th scope="row">9</th>
          <td>Larry</td>
          <td>the Bird</td>
          <td>@twitter</td>
        </tr>
        <tr>
          <th scope="row">10</th>
          <td>Mark</td>
          <td>Otto</td>
          <td>@mdo</td>
        </tr>
        <tr>
          <th scope="row">11</th>
          <td>Jacob</td>
          <td>Thornton</td>
          <td>@fat</td>
        </tr>
        <tr>
          <th scope="row">12</th>
          <td>Larry</td>
          <td>the Bird</td>
          <td>@twitter</td>
        </tr>
        <tr>
          <th scope="row">13</th>
          <td>Mark</td>
          <td>Otto</td>
          <td>@mdo</td>
        </tr>
        <tr>
          <th scope="row">14</th>
          <td>Jacob</td>
          <td>Thornton</td>
          <td>@fat</td>
        </tr>
        <tr>
          <th scope="row">15</th>
          <td>Larry</td>
          <td>the Bird</td>
          <td>@twitter</td>
        </tr>
        <tr>
          <th scope="row">16</th>
          <td>Mark</td>
          <td>Otto</td>
          <td>@mdo</td>
        </tr>
        <tr>
          <th scope="row">17</th>
          <td>Jacob</td>
          <td>Thornton</td>
          <td>@fat</td>
        </tr>
        <tr>
          <th scope="row">18</th>
          <td>Larry</td>
          <td>the Bird</td>
          <td>@twitter</td>
        </tr>
      </tbody>
    </table>

    <div class="page-break"></div>

    <p>
      A page break means that this content starts on a new page.
    </p>

    <h2 class="primary">
      Primary text
    </h2>

    <p class="primary">
      This paragraph and associated title is in the <?=htmlspecialchars(app()->tenant->getKey('CLUB_NAME'))?> Membership House Colour
    </p>

    <h2>
      Primary box
    </h2>

    <div class="primary-box mb-3" id="test">
      <h2>
        White text in a primary box
      </h2>

      <p class="mb-0">
        This paragraph and associated title is white in a box which is in the <?=htmlspecialchars(app()->tenant->getKey('CLUB_NAME'))?> Membership House Colour
      </p>
    </div>
    <?php include BASE_PATH . 'helperclasses/PDFStyles/PageNumbers.php'; ?>
  </body>
</html>

<?php

$html = ob_get_clean();

// reference the Dompdf namespace
use Dompdf\Dompdf;

// instantiate and use the dompdf class
$dompdf = new Dompdf();

// set font dir here
$dompdf->set_option('font_dir', BASE_PATH . 'fonts/');

$dompdf->set_option('defaultFont', 'Open Sans');
$dompdf->set_option('defaultMediaType', 'all');
$dompdf->set_option("isPhpEnabled", true);
$dompdf->set_option('isFontSubsettingEnabled', false);
$dompdf->loadHtml($html);

// (Optional) Setup the paper size and orientation
$dompdf->setPaper('A4', 'portrait');

// Render the HTML as PDF
$dompdf->render();

// Output the generated PDF to Browser
header('Content-Description: File Transfer');
header('Content-Type: application/pdf');
header('Content-Disposition: inline');
header('Expires: 0');
header('Cache-Control: must-revalidate');
header('Pragma: public');
$dompdf->stream("TestPDF.pdf", ['Attachment' => 0]);
